name: murarkey_app
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

#  flutter clean && flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
dependencies:
  flutter:
    sdk: flutter
  #  auto_route: ^0.2.1
  carousel_slider: ^3.0.0
  flutter_svg: ^0.22.0 #^0.19.2+1
  #websafe_svg: ^1.1.4+2
  #  flutter_svg: ^0.21.0

  #Facebook messaging
  #  facebook_share: ^1.0.0
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #A Flutter plugin for launching a URL.
  #Supports iOS, Android, web, Windows, macOS, and Linux.
  url_launcher: ^6.0.6

  # it easy to consume HTTP resources
  http: ^0.13.0
  http_parser: ^4.0.0

  #json serialization library
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1

  # persistent storage for simple data
  shared_preferences: 2.0.6

#  flutter_plugin_android_lifecycle: 1.0.3
#  image_picker: 0.6.2+3
  image_picker: ^0.8.1+1

  # esewa payment
  #  esewa_pnp: 1.0.7

  #PayPal / Venmo / 3D Secure payment
  flutter_braintree: 2.0.0
  #  flutter_braintree: 1.2.0

  # loading indicators
  flutter_spinkit: "^4.1.2"

  #rendering HTML and CSS as Flutter widgets
  flutter_html: ^2.1.0
  webview_flutter: ^2.0.4

  #google sign in
  firebase_core:
  firebase_auth: 3.1.1
  google_sign_in: 5.1.0

  #state management
  provider: 6.0.0

  progress_dialog: 1.2.4
  slugify: 2.0.0

  #filter_list: 1.0.1
  smart_select: 4.3.2
  chips_choice: 2.0.1

  # todo end of dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/our_services/
    - images/arrows/
    - images/maths/
    - images/cart/
    - images/money/
    - assets/epay_request.html
  #     - images/app_logo.jpg
  #     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
